Repository mash-up-kr/WeQuiz-Android, pull requests merged in 2023-08, with the labels that each got.

#125 [문제풀기 #88] 문제풀기 잔여 뷰 작업
  app/src/main/res/layout/fragment_quiz_fetch_failed.xml
  app/src/main/res/layout/fragment_quiz_solve.xml
  app/src/main/res/layout/fragment_quiz_solve_enter.xml
  app/src/main/res/layout/fragment_solve_personal_information.xml
  app/src/main/res/layout/item_quiz_solve_answer.xml
  app/src/main/res/values/strings.xml
  design-resource/src/main/res/drawable/bg_28292a_radius_10.xml
  design-resource/src/main/res/drawable/bg_radius_16.xml
  design-resource/src/main/res/drawable/gradient_progressbar.xml
  design-resource/src/main/res/drawable/ic_home.xml
  design-resource/src/main/res/drawable/icon_siren.xml
  design-resource/src/main/res/drawable/img_qui_solve.png
Labels: 현수, 🖥 View

#127 [회원가입/로그인] 서버 API 연결
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/IntroViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/join/JoinFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/onboarding/OnboardingFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/verifycode/VerifyCodeFragment.kt
  app/src/main/res/navigation/intro_nav_graph.xml
  data/src/main/kotlin/team/ommaya/wequiz/android/data/mapper/UserMapper.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/user/SignUpRequest.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/user/SignUpResponse.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/user/UserInformationFormattedResponse.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/user/UserInformation.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/UserRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/ResendPhoneVerificationUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/SetAuthCallbacksUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/SignUpUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/StartPhoneVerificationUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/VerifyCodeUseCase.kt
Labels: 재훈, 🎱 feature

#130 [회원가입/로그인] 자동로그인 구현
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/IntroActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/IntroViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/verifycode/VerifyCodeFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/welcome/WelcomeFragment.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/preference/UserPreferenceSerializer.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/preference/UserPrefernce.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/user/User.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/UserRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/user/SaveTokenUseCase.kt
Labels: 재훈, 🎱 feature

#132 홈 액티비티 최종 연결
  app/src/main/kotlin/team/ommaya/wequiz/android/home/friends/FriendsRankActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizdetail/QuizDetailActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizlist/QuizListActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/utils.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/UserRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/user/UserLogoutUseCase.kt
Labels: 💪 enhancement, 성빈

#135 로그아웃 UI 추가
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizlist/QuizListScreen.kt
  app/src/test/resources/robolectric.properties
Labels: 성빈, 🖥 View

#136 [회원가입/로그인] Firebase Play Integrity API 작업 외 기타 작업
  app/src/main/kotlin/team/ommaya/wequiz/android/MainActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/IntroActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/IntroViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/phone/PhoneFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/verifycode/VerifyCodeFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/welcome/WelcomeFragment.kt
  app/src/main/res/values/strings.xml
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/FirebaseRepositoryImpl.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/AuthCallbacksListener.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/FirebaseRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/user/SetPlayIntegrityUseCase.kt
  gradle/libs.versions.toml
Labels: 재훈, fixed

#138 CancellationException 인터렙트 버그 해결
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/SuspendCatching.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/ResendPhoneVerificationUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/SetAuthCallbacksUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/SignUpUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/StartPhoneVerificationUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/VerifyCodeUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/CreateQuizUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/DeleteQuizUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/GetAnonymousTokenUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/GetQuizDetailUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/GetQuizListUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/GetQuizRankUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/GetSolveRankUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/SubmitQuizAnswerUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/statistic/GetQuizStatisticUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/user/GetUserInformationUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/user/SaveTokenUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/user/UserLogoutUseCase.kt
Labels: 성빈, fixed

#139 [잡일] 신고하기 다이얼로그 및 결과 공유 정책 변경
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/solve/QuizSolveFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/solve/QuizSolveSharedViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/solve/result/ResultFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/solve/result/ResultRankingFragment.kt
  app/src/main/res/layout/fragment_quiz_solve.xml
  app/src/main/res/values/strings.xml
Labels: 현수, 🎱 feature, fixed

#141 [로그인/회원가입 #140] 인증번호 오류 수정
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/IntroViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/phone/PhoneFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/solve/QuizSolveFragment.kt
  app/src/main/res/values/strings.xml
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/FirebaseRepositoryImpl.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/AuthCallbacksListener.kt
Labels: 재훈, fixed

#149 [회원가입/로그인, 홈] 디자인 QA 수정
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/onboarding/OnboardingFragment.kt
  app/src/main/res/drawable/ic_color_grade_bronze_24.xml
  app/src/main/res/drawable/ic_color_grade_gold_24.xml
  app/src/main/res/drawable/ic_color_grade_silver_24.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/fragment_verify_code.xml
Labels: 재훈, fixed
