Repository mash-up-kr/WeQuiz-Android, pull requests merged in 2023-07, with the labels that each got.

#64 홈 메인 화면 추가
  app/build.gradle.kts
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/constraints.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/measurables.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/paint.kt
  app/src/main/res/drawable/ic_color_grade_bronze_24.xml
  app/src/main/res/drawable/ic_color_grade_gold_24.xml
  app/src/main/res/drawable/ic_color_grade_silver_24.xml
  app/src/main/res/drawable/ic_fill_document_24.xml
  app/src/main/res/drawable/ic_round_chevron_right_24.xml
  app/src/test/kotlin/team/ommaya/wequiz/android/HomeMainScreenSnapshot.kt
  app/src/test/snapshots/HomeMainScreen/Empty.png
  app/src/test/snapshots/HomeMainScreen/FriendsRankingAndExam.png
  app/src/test/snapshots/HomeMainScreen/OnlyExam.png
  design-resource-compose/src/main/kotlin/team/ommaya/wequiz/android/design/resource/compose/color.kt
  design-resource-compose/src/main/kotlin/team/ommaya/wequiz/android/design/resource/compose/typography.kt
  gradle/libs.versions.toml
Labels: 성빈, 🖥 View

#66 친구 목록 컴포저블 분리
  .editorconfig
  app/src/main/kotlin/team/ommaya/wequiz/android/home/FriendsRank.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/HomeMainScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/applyIf.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/FriendsRankSnapshot.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/HomeMainScreenSnapshot.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/dummy/dummy.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/rule/SnapshotPathGeneratorRule.kt
  app/src/test/snapshots/FriendsRank/Full.png
  app/src/test/snapshots/HomeMainScreen/FriendsRankingAndExam.png
Labels: 성빈, 🖥 View

#68 문제 리스트 컴포저블 구현
  .run/app.run.xml
  app/build.gradle.kts
  app/src/main/kotlin/team/ommaya/wequiz/android/home/ExamList.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/FriendsRank.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/HomeMainScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/clickable.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/paint.kt
  app/src/main/res/drawable/ic_fill_file_tray_24.xml
  app/src/main/res/drawable/ic_fill_minus_circle_24.xml
  app/src/test/kotlin/team/ommaya/wequiz/android/ExamListSnapshot.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/dummy/dummy.kt
  app/src/test/snapshots/ExamList/DeleteModeOff.png
  app/src/test/snapshots/ExamList/DeleteModeOn.png
  app/src/test/snapshots/FriendsRank/Full.png
  app/src/test/snapshots/HomeMainScreen/Empty.png
  app/src/test/snapshots/HomeMainScreen/FriendsRankingAndExam.png
  app/src/test/snapshots/HomeMainScreen/OnlyExam.png
Labels: 성빈, 🖥 View

#76 [회원가입/로그인] 다이얼로그 프래그먼트 추가
  app/src/main/kotlin/team/ommaya/wequiz/android/base/BaseViewBindingDialogFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/verifycode/SingUpDialog.kt
  app/src/main/res/layout/dialog_sign_up.xml
  design-resource/src/main/res/drawable/btn_radius_16.xml
Labels: 재훈, 🎱 feature, 🖥 View

#78 홈/퀴즈 디테일 화면 구현
  .gitattributes
  .gitignore
  app/build.gradle.kts
  app/src/main/kotlin/team/ommaya/wequiz/android/home/DummyQuizDetailActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/HomeMainScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/QuizDetail.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/QuizList.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/ExamListSnapshot.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/HomeMainScreenSnapshot.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/dummy/dummy.kt
  app/src/test/snapshots/ExamList/DeleteModeOff.png
  app/src/test/snapshots/ExamList/DeleteModeOn.png
  app/src/test/snapshots/FriendsRank/Full.png
  app/src/test/snapshots/HomeMainScreen/Empty.png
  app/src/test/snapshots/HomeMainScreen/FriendsRankingAndExam.png
  app/src/test/snapshots/HomeMainScreen/OnlyExam.png
  gradle/libs.versions.toml
Labels: 💪 enhancement, 성빈, 🖥 View

#84 [공통] WeQuizDialog util 추가
  app/src/main/kotlin/team/ommaya/wequiz/android/base/BaseViewBindingDialogFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/verifycode/SingUpDialog.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/WeQuizDialog.kt
  app/src/main/res/layout/dialog_we_quiz.xml
Labels: 💪 enhancement, 재훈, 🖥 View

#81 [공통] 스낵바 추가
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/join/JoinFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/phone/PhoneFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/Extensions.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/WeQuizSnackbar.kt
  app/src/main/res/layout/snackbar_wequiz.xml
  app/src/main/res/values/theme.xml
  design-resource/src/main/res/drawable/bg_radius_8.xml
  design-resource/src/main/res/drawable/ic_chevron_right_medium.xml
  design-resource/src/main/res/drawable/ic_circle_failure.xml
  design-resource/src/main/res/drawable/ic_circle_success.xml
  design-resource/src/main/res/values/colors.xml
  design-resource/src/main/res/values/styles.xml
Labels: 재훈, 🎱 feature, 🖥 View

#80 [문제만들기] 포커스에 따른 expand와 스크롤 처리
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/Question.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/QuizCreateActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/QuizCreateViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/adapter/AnswerAdapter.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/adapter/QuizCreateAdapter.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/viewholder/AnswerAddViewHolder.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/viewholder/AnswerViewHolder.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/viewholder/QuestionAddViewHolder.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/viewholder/QuestionViewHolder.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/viewholder/QuizCreateViewHolder.kt
  app/src/main/res/layout/activity_quiz_create.xml
  app/src/main/res/layout/item_quiz_create_quiz.xml
Labels: 현수, 🖥 View

#89 [회원가입/로그인] 타이머 추가
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/IntroViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/onboarding/OnboardingFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/phone/PhoneFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/verifycode/VerifyCodeFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/WeQuizSnackbar.kt
  app/src/main/res/layout/fragment_verify_code.xml
  app/src/main/res/navigation/intro_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 재훈, 🎱 feature, 🖥 View

#90 Integrate each Composable into an Activity or Fragment
  app/src/main/kotlin/team/ommaya/wequiz/android/home/DummyQuizDetailActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/friends/FriendsRankActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/friends/FriendsRankScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizdetail/QuizDetailActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizdetail/QuizDetailScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizlist/QuizListActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizlist/QuizListScreen.kt
  app/src/main/res/drawable/ic_outline_search_24.xml
  app/src/main/res/drawable/ic_round_chevron_left_24.xml
  app/src/main/res/drawable/ic_round_share_24.xml
  app/src/main/res/drawable/ic_round_trash_24.xml
  app/src/test/kotlin/team/ommaya/wequiz/android/ExamListSnapshot.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/FriendsRankSnapshot.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/HomeMainScreenSnapshot.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/dummy/dummy.kt
Labels: 💪 enhancement, 성빈, 🖥 View

#93 홈에 사용되는 API 추가
  data/src/main/kotlin/team/ommaya/wequiz/android/data/client/HttpClient.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/di/DataStoreModule.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/mapper/RankMapper.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/mapper/UserMapper.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/rank/RankResponse.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/rank/RankingsItemResponse.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/rank/UserSimpleInformationResponse.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/user/UserInformationResponse.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/preference/UserPreferenceSerializer.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/preference/UserPrefernce.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/RankRepositoryImpl.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/UserRepositoryImpl.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/repository/UserRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/rank/Rank.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/rank/RankingsItem.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/rank/UserSimpleInformation.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/user/User.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/user/UserInformation.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/RankRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/UserRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/GetMyQuizRankUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/user/GetUserInformationUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/user/GetUserUseCase.kt
Labels: 💪 enhancement, 성빈

#96 [문제만들기 #72] 뷰 관련 인터랙션 처리 및 상태 저장
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/Question.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/QuizCreateActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/QuizCreateFinishFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/QuizCreateFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/QuizCreateSharedViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/QuizCreateViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/adapter/AnswerAdapter.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/adapter/QuizCreateAdapter.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/viewholder/AnswerAddViewHolder.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/viewholder/AnswerViewHolder.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/viewholder/QuestionAddViewHolder.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/viewholder/QuestionViewHolder.kt
  app/src/main/res/layout/activity_quiz_create.xml
  app/src/main/res/layout/fragment_quiz_create.xml
  app/src/main/res/layout/fragment_quiz_create_finish.xml
  app/src/main/res/layout/item_quiz_answer.xml
  app/src/main/res/layout/item_quiz_create_quiz.xml
  app/src/main/res/navigation/quiz_create_graph.xml
  app/src/main/res/values/strings.xml
  design-resource/src/main/res/drawable/bg_p1_radius_16.xml
  design-resource/src/main/res/drawable/ic_answer_correct.xml
Labels: 현수, 🎱 feature, 🖥 View

#102 [문제만들기 #97] 만들기 api 붙히기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/team/ommaya/wequiz/android/WeQuizApp.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/Question.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/QuizCreateActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/QuizCreateFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/create/QuizCreateViewModel.kt
  build.gradle.kts
  data/src/main/kotlin/team/ommaya/wequiz/android/data/client/HttpClient.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/mapper/QuizMapper.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/quiz/QuizCreateRequest.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/quiz/QuizCreateResponse.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/QuizRepositoryImpl.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/quiz/Option.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/quiz/Question.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/QuizRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/CreateQuizUseCase.kt
Labels: 💪 enhancement, 현수

#104 [회원가입/로그인 #82] Firebase Auth Phone Number Verification 구현
  .gitignore
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/IntroActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/IntroViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/join/JoinFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/onboarding/OnboardingFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/phone/PhoneFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/verifycode/VerifyCodeFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/welcome/WelcomeFragment.kt
  app/src/main/res/layout/fragment_verify_code.xml
  data/build.gradle.kts
  data/src/main/kotlin/team/ommaya/wequiz/android/data/di/FirebaseModule.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/FirebaseAuthRepositoryImpl.kt
  design-resource/src/main/res/values/colors.xml
  domain/build.gradle.kts
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/AuthCallbacksListener.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/FirebaseAuthRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/ResendPhoneVerificationUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/SetAuthCallbacksUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/StartPhoneVerificationUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/intro/VerifyCodeUseCase.kt
  gradle/libs.versions.toml
Labels: 재훈, 🎱 feature

#107 [회원가입/로그인 #100] 뷰 수정사항 반영 & 입력 컴포넌트 변경
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/IntroViewModel.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/join/JoinFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/phone/PhoneFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/verifycode/VerifyCodeFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/intro/welcome/WelcomeFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_join.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/fragment_phone.xml
  app/src/main/res/layout/fragment_verify_code.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/navigation/intro_nav_graph.xml
  app/src/main/res/values/strings.xml
  design-resource/src/main/res/drawable/bg_onboarding.png
  design-resource/src/main/res/drawable/img_we_quiz_onboarding.png
  design-resource/src/main/res/drawable/img_we_quiz_welcome.png
  design-resource/src/main/res/values/styles.xml
Labels: 재훈, 🎱 feature, 🖥 View

#114 홈 스크린 API 연결
  app/src/main/kotlin/team/ommaya/wequiz/android/home/friends/FriendsRankActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/friends/FriendsRankScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizdetail/QuizDetailActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizdetail/QuizDetailScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizlist/QuizListActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizlist/QuizListScreen.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/toast.kt
  app/src/main/res/drawable/ic_color_profile_image.xml
  app/src/test/kotlin/team/ommaya/wequiz/android/FriendsRankSnapshot.kt
  app/src/test/kotlin/team/ommaya/wequiz/android/HomeMainScreenSnapshot.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/mapper/QuizMapper.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/quiz/OptionsItem.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/quiz/QuestionsItem.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/quiz/QuizDetailResponse.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/quiz/QuizItem.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/model/quiz/QuizListResponse.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/QuizRepositoryImpl.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/repository/RankRepositoryImpl.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/quiz/Quiz.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/quiz/QuizDetail.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/quiz/QuizDetailOption.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/quiz/QuizDetailQuestion.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/quiz/QuizList.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/QuizRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/RankRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/DeleteQuizUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/GetQuizDetailUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/GetQuizListUseCase.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/quiz/GetQuizRankUseCase.kt
Labels: 성빈, 🖥 View

#118 홈 화면 액티비티로 변경
  app/src/main/kotlin/team/ommaya/wequiz/android/home/friends/FriendsRankActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/main/HomeMainFragment.kt
Labels: 성빈, 🖥 View

#119 퀴즈 디테일 액티비티 UI 완성
  app/src/main/kotlin/team/ommaya/wequiz/android/home/common/QuizDeleteConfirmDialog.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizdetail/QuizDetailActivity.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/home/quizlist/QuizListActivity.kt
Labels: 성빈, 🖥 View

#115 [시험지 풀기 #88] 시험지 풀기 베이스 뷰 작업 (결과 화면)
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/solve/result/Ranking.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/solve/result/ResultFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/solve/result/ResultRankingFragment.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/solve/result/adapter/ResultRankingAdapter.kt
  app/src/main/kotlin/team/ommaya/wequiz/android/quiz/solve/result/viewholder/ResultRankingViewHolder.kt
  app/src/main/res/layout/fragment_result.xml
  app/src/main/res/layout/fragment_result_ranking.xml
  app/src/main/res/layout/item_quiz_solve_ranking.xml
  app/src/main/res/values/strings.xml
  design-resource/src/main/res/drawable/bg_ranking_bottom.xml
  design-resource/src/main/res/drawable/btn_radius_19.xml
  design-resource/src/main/res/drawable/ic_grade_bronze.xml
  design-resource/src/main/res/drawable/ic_grade_gold.xml
  design-resource/src/main/res/drawable/ic_grade_silver.xml
  design-resource/src/main/res/drawable/ic_home.xml
  design-resource/src/main/res/drawable/ic_result_fight.xml
  design-resource/src/main/res/drawable/ic_result_jjinchin.xml
  design-resource/src/main/res/drawable/ic_result_run.xml
  design-resource/src/main/res/values/colors.xml
Labels: 재훈, 🖥 View
