Repository mash-up-kr/WeQuiz-Android, pull requests merged in 2023-06, with the labels that each got.

#16 홈 모듈 및 컨벤션 플러그인 등록
  build-logic/build.gradle.kts
  build-logic/gradle.properties
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/build-logics.kt
  build-logic/src/main/kotlin/internal/android.kt
  build-logic/src/main/kotlin/internal/compose.kt
  build-logic/src/main/kotlin/internal/constants.kt
  build-logic/src/main/kotlin/internal/extensions.kt
  build-logic/src/main/kotlin/plugins.kt
  build-logic/src/main/kotlin/public-extensions.kt
  buildSrc/build.gradle.kts
  buildSrc/gradle.properties
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/plugin.kt
  gradle/libs.versions.toml
  home/friend-rank/build.gradle.kts
  home/friend-rank/src/main/AndroidManifest.xml
  home/friend-rank/src/main/kotlin/team/ommaya/wequiz/android/home/friend/rank/todo
  home/main/build.gradle.kts
  home/main/src/main/AndroidManifest.xml
  home/main/src/main/kotlin/team/ommaya/wequiz/android/home/main/todo
  home/profile-edit/build.gradle.kts
  home/profile-edit/src/main/AndroidManifest.xml
  home/profile-edit/src/main/kotlin/team/ommaya/wequiz/android/home/profile/edit/todo
  home/quiz-detail/build.gradle.kts
  home/quiz-detail/src/main/AndroidManifest.xml
  home/quiz-detail/src/main/kotlin/team/ommaya/wequiz/android/home/quiz/detail/todo
  home/quiz-list/build.gradle.kts
  home/quiz-list/src/main/AndroidManifest.xml
  home/quiz-list/src/main/kotlin/team/ommaya/wequiz/android/home/quiz/list/todo
  settings.gradle.kts
Labels: enhancement

#35 컴포즈용 디자인 리소스 추가
  .editorconfig
  .gitattributes
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/dictionaries/jisungbin.xml
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/build-logics.kt
  design-resource-compose/build.gradle.kts
  design-resource-compose/src/main/AndroidManifest.xml
  design-resource-compose/src/main/kotlin/team/ommaya/wequiz/android/design/resource/compose/color.kt
  design-resource-compose/src/main/kotlin/team/ommaya/wequiz/android/design/resource/compose/gradient.kt
  design-resource-compose/src/main/kotlin/team/ommaya/wequiz/android/design/resource/compose/typography.kt
  design-resource-compose/src/main/res/font/drc_pretendard_bold.otf
  design-resource-compose/src/main/res/font/drc_pretendard_medium.otf
  design-resource-compose/src/main/res/font/drc_pretendard_regular.otf
  design-resource-compose/src/main/res/font/drc_pretendard_semi_bold.otf
  design-resource-compose/src/test/kotlin/team/ommaya/wequiz/android/design/resource/compose/WeQuizGradientSnapshot.kt
  design-resource-compose/src/test/snapshots/WeQuizGradient/black.png
  design-resource-compose/src/test/snapshots/WeQuizGradient/secondary.png
  detekt-config.yml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement, gradle

#44 프로젝트 정리
  .github/workflows/android-ci.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/team/ommaya/wequiz/android/MainActivity.kt
  build-logic/build.gradle.kts
  build-logic/gradle.properties
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/build-logics.kt
  build-logic/src/main/kotlin/internal/android.kt
  build-logic/src/main/kotlin/internal/compose.kt
  build-logic/src/main/kotlin/internal/constants.kt
  build-logic/src/main/kotlin/internal/extensions.kt
  build-logic/src/main/kotlin/plugins.kt
  build-logic/src/main/kotlin/public-extensions.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/plugin.kt
  design-resource-compose/build.gradle.kts
  design-resource/build.gradle.kts
  design-resource/src/main/res/values-v26/typography.xml
  design-resource/src/main/res/values-v28/typography.xml
  design-resource/src/main/res/values/typography.xml
  detekt-config.yml
  gradle.properties
  gradle/libs.versions.toml
  home/friend-rank/build.gradle.kts
  home/friend-rank/src/main/AndroidManifest.xml
  home/friend-rank/src/main/kotlin/team/ommaya/wequiz/android/home/friend/rank/todo
  home/main/build.gradle.kts
  home/main/src/main/AndroidManifest.xml
  home/main/src/main/kotlin/team/ommaya/wequiz/android/home/main/todo
  home/profile-edit/build.gradle.kts
  home/profile-edit/src/main/AndroidManifest.xml
  home/profile-edit/src/main/kotlin/team/ommaya/wequiz/android/home/profile/edit/todo
  home/quiz-detail/build.gradle.kts
  home/quiz-detail/src/main/AndroidManifest.xml
  home/quiz-detail/src/main/kotlin/team/ommaya/wequiz/android/home/quiz/detail/todo
  home/quiz-list/build.gradle.kts
  home/quiz-list/src/main/AndroidManifest.xml
  home/quiz-list/src/main/kotlin/team/ommaya/wequiz/android/home/quiz/list/todo
  join/build.gradle.kts
  join/src/main/AndroidManifest.xml
  join/src/main/java/team/ommaya/wequiz/android/join/JoinActivity.kt
  join/src/main/res/layout/activity_join.xml
  quiz/create/build.gradle.kts
  quiz/create/src/main/AndroidManifest.xml
  quiz/create/src/main/java/team/ommaya/wequiz/quiz/create/QuizCreateActivity.kt
  quiz/create/src/main/res/layout/activity_quiz_create.xml
  quiz/create/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 💪 enhancement, gradle, dependencies, 성빈

#46 프로젝트 정리
  .github/workflows/android-ci.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/team/ommaya/wequiz/android/MainActivity.kt
  build-logic/build.gradle.kts
  build-logic/gradle.properties
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/build-logics.kt
  build-logic/src/main/kotlin/internal/android.kt
  build-logic/src/main/kotlin/internal/compose.kt
  build-logic/src/main/kotlin/internal/constants.kt
  build-logic/src/main/kotlin/internal/extensions.kt
  build-logic/src/main/kotlin/plugins.kt
  build-logic/src/main/kotlin/public-extensions.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/plugin.kt
  design-resource-compose/build.gradle.kts
  design-resource/build.gradle.kts
  design-resource/src/main/AndroidManifest.xml
  design-resource/src/main/res/values-v26/typography.xml
  design-resource/src/main/res/values-v28/typography.xml
  design-resource/src/main/res/values/strings.xml
  design-resource/src/main/res/values/typography.xml
  detekt-config.yml
  gradle.properties
  gradle/libs.versions.toml
  home/friend-rank/build.gradle.kts
  home/friend-rank/src/main/AndroidManifest.xml
  home/friend-rank/src/main/kotlin/team/ommaya/wequiz/android/home/friend/rank/todo
  home/main/build.gradle.kts
  home/main/src/main/AndroidManifest.xml
  home/main/src/main/kotlin/team/ommaya/wequiz/android/home/main/todo
  home/profile-edit/build.gradle.kts
  home/profile-edit/src/main/AndroidManifest.xml
  home/profile-edit/src/main/kotlin/team/ommaya/wequiz/android/home/profile/edit/todo
  home/quiz-detail/build.gradle.kts
  home/quiz-detail/src/main/AndroidManifest.xml
  home/quiz-detail/src/main/kotlin/team/ommaya/wequiz/android/home/quiz/detail/todo
  home/quiz-list/build.gradle.kts
  home/quiz-list/src/main/AndroidManifest.xml
  home/quiz-list/src/main/kotlin/team/ommaya/wequiz/android/home/quiz/list/todo
  join/build.gradle.kts
  join/src/main/AndroidManifest.xml
  join/src/main/java/team/ommaya/wequiz/android/join/JoinActivity.kt
  join/src/main/res/layout/activity_join.xml
  quiz/create/build.gradle.kts
  quiz/create/src/main/AndroidManifest.xml
  quiz/create/src/main/java/team/ommaya/wequiz/quiz/create/QuizCreateActivity.kt
  quiz/create/src/main/res/layout/activity_quiz_create.xml
  quiz/create/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 💪 enhancement, gradle, dependencies, 성빈

#51 HttpClient 구성 (ktor-client 사용)
  app/src/main/AndroidManifest.xml
  data/build.gradle.kts
  data/src/main/kotlin/team/ommaya/wequiz/android/data/HttpClient.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/data/todo
  gradle/libs.versions.toml
Labels: 💪 enhancement, gradle, dependencies, 성빈

#53 함수명 오타 수정
  data/src/main/kotlin/team/ommaya/wequiz/android/data/HttpClient.kt
Labels: 성빈

#52 datastore setting 작업
  data/build.gradle.kts
  data/src/main/kotlin/team/ommaya/wequiz/android/di/DataStoreModule.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/di/RepositoryModule.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/preference/UserPreferenceSerializer.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/preference/UserPrefernce.kt
  data/src/main/kotlin/team/ommaya/wequiz/android/repository/UserRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/model/User.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/repository/UserRepository.kt
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/todo
  domain/src/main/kotlin/team/ommaya/wequiz/android/domain/usecase/GetUserUseCase.kt
  gradle/libs.versions.toml
Labels: 현수, 🎱 feature

#59 공통 버튼 스타일 작성
  app/build.gradle.kts
  app/src/main/res/layout/activity_main.xml
  design-resource-compose/src/test/kotlin/team/ommaya/wequiz/android/design/resource/compose/WeQuizGradientSnapshot.kt
  design-resource-compose/src/test/snapshots/WeQuizGradient/black.png
  design-resource-compose/src/test/snapshots/WeQuizGradient/secondary.png
  design-resource/src/main/res/drawable/btn_radius_12.xml
  design-resource/src/main/res/values/styles.xml
Labels: 💪 enhancement, 현수, 🖥 View

#61 공통 input 스타일 작성
  app/build.gradle.kts
  app/src/main/kotlin/team/ommaya/wequiz/android/utils/TextInputLayoutExtensions.kt
  app/src/main/res/layout/activity_main.xml
  design-resource/build.gradle.kts
  design-resource/src/main/res/color/selector_text_input_layer_hint_text_color.xml
  design-resource/src/main/res/color/selector_text_input_layer_indicator.xml
  design-resource/src/main/res/drawable/btn_radius_4.xml
  design-resource/src/main/res/drawable/btn_resend_certification.xml
  design-resource/src/main/res/values/styles.xml
  gradle/libs.versions.toml
Labels: 💪 enhancement, 재훈, 🖥 View
